"""Add doctors table

Revision ID: 2b3c9ed75196
Revises: efb14a7b1183
Create Date: 2025-06-20 00:24:37.987261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2b3c9ed75196'
down_revision: Union[str, None] = 'efb14a7b1183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctors_id'), table_name='doctors')
    op.drop_table('doctors')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('specialty', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('rating', mysql.FLOAT(), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('image_url', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('review_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_doctors_id'), 'doctors', ['id'], unique=False)
    # ### end Alembic commands ###
