"""remove status to appointments

Revision ID: 531b1cf38e02
Revises: 1ff078e9e675
Create Date: 2025-06-20 17:47:59.081482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '531b1cf38e02'
down_revision: Union[str, None] = '1ff078e9e675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('status', mysql.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
