"""add profile_pic and fields to User model

Revision ID: ac1e2b5de76b
Revises: aa69946d2bdb
Create Date: 2025-06-18 12:22:26.373657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ac1e2b5de76b'
down_revision: Union[str, None] = 'aa69946d2bdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('fullname', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('profile_pic', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('nickname', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('anotheremail', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('dateofbirth', sa.String(length=20), nullable=True))
    op.drop_index(op.f('phone'), table_name='users')
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'phone')
    op.drop_column('users', 'dob')
    op.drop_column('users', 'name')
    op.drop_column('users', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('users', sa.Column('dob', mysql.VARCHAR(length=15), nullable=True))
    op.add_column('users', sa.Column('phone', mysql.VARCHAR(length=15), nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('phone'), 'users', ['phone'], unique=True)
    op.drop_column('users', 'dateofbirth')
    op.drop_column('users', 'anotheremail')
    op.drop_column('users', 'nickname')
    op.drop_column('users', 'profile_pic')
    op.drop_column('users', 'fullname')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
